### ISSUE TITLE
Shift + Delete doesn't work as expected

### ISSUE THREAD

**Issue by giangnvt** [gourdo1/gmmkpro-media#2]
Thanks for your great work. 
Tried about a week, worked better than original firmware. 
Only one issue though, not sure whether a bug or not, but if I press Shift + Del button, it doesn't give the same effect as a  normal keyboard (like permanently delete something).

**Comment by gourdo1** [comment]
Can you open a text editor and hit [Fn]` (tilde key) and tell me what the "DEL & HOME key locations" setting is?

By default, the DEL key is right of backspace and HOME is above backspace, but you can reverse them with [Fn]4.

In Windows Explorer, I get the expected "Are you sure you want to permanently delete this file?' dialog when I use SHIFT-Delete, so seems to be working here...

**Comment by giangnvt** [comment]
> Can you open a text editor and hit [Fn]` (tilde key) and tell me what the "DEL & HOME key locations" setting is?
> 
> By default, the DEL key is right of backspace and HOME is above backspace, but you can reverse them with [Fn]4

I know that fact, and have confirmed that the Home / Del key mapping is correct before submitting this issue.
Anyway, this is your requested output:

Config also visible as RGB under number keys by holding [Fn].
----------------------------------------------------------------------
1. CapsLock RGB highlight alpha keys................ [OFF]
2. Numpad RGB highlight layer keys.................. [ON]
3. Double tap ESC to revert to BASE layer........... [ON]
4. DEL & HOME key locations......................... [HOME on F13; DEL right of BKSPC]
5. Numpad on CapsLock; double tap LSHIFT for Caps... [OFF]
6. Encoder button function.......................... [MUTE]
7. Insert function accessed with.................... [SHIFT-DEL]
8. Force SHIFT & CTRL-SPACE to function like SPACE.. [OFF]
9. AutoCorrect...................................... [OFF]
0. CapsLock highlights extended alphas (ISO-only)... [OFF]

**Comment by gourdo1** [comment]
Ok, so Shift-DEL is mapped to Insert. [Fn]7 to toggle it to Shift-BACKSPC (default)... Then Shift-DEL should work as expected.

**Comment by fpt-giangnvt** [comment]
@gourdo1 
Can't believe I missed that setting at #7.
Disable it and everything works as expected now.

By the way, regards the fact that many Windows user may prefer to use Shift + Del as its default behavior, and still need the Insert key to be available at the same time, would you please consider to implement a different mapping for Insert key other than Shift + Del (something like Fn + Del, or Fn + Backspace).
Thanks.

**Comment by gourdo1** [comment]
So the default is that Shift-DEL works normally and Insert is on Shift-BCKSPC, so Insert IS available by default. For some reason you must have inadvertently hit Fn-7 at some point... You can verify this by resetting your EEPROM with Fn-ESC.

I'm using the Fn layer only for settings, layer control and RGB right now, so not sure I want to map actual functional keys to it... But you can always use VIA (https://usevia.app/) to do your own customizations if Shift-BCKSPC doesn't work for you.
